# Stage 1: Build
FROM node:18-alpine AS builder

ARG VITE_API_BASE_URL_ARG=/api
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL_ARG

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build

# Stage 2: Serve
FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]