# environment.yml
name: audio_app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - pip:
    - fastapi
    - uvicorn[standard] # Includes websockets, http-tools, etc.
    - python-dotenv
    - pydantic >=2.0
    - pydantic-settings
    - celery[redis]
    - sqlalchemy
    - redis
    - pyttsx3
    - elevenlabs
    - kokoro_onnx
    - soundfile